builds:
  - main: ./starport/cmd/starport
    ldflags:
      - -s -w -X github.com/tendermint/starport/starport/internal/version.Version={{.Tag}} -X github.com/tendermint/starport/starport/internal/version.Date={{.Date}}
    goarch:
      - amd64
changelog:
  skip: true
release:
  prerelease: true
