name: Generate Protoc Dart Plugin 

on:
  push:
    branches:
      - develop

jobs:
  dart:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Generate Dart files
        run: ./scripts/gen-protoc-gen-dart

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "feat(pkg/protoc-gen-dart): update binary on ${{ matrix.os }}"
          commit-message: "feat(pkg/protoc-gen-dart): update binary on ${{ matrix.os }}"
          body: ""
          branch: feat/gen-pgd-${{ matrix.os }}

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
