name: Lint
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@master
        with:
          version: v1.36.0
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
          skip-go-installation: true
