name: Release

on:
  push:
    tags:
      - "*"

jobs:
  binary:
    runs-on: ubuntu-latest
    env:
      working-directory: go/src/github.com/tendermint/starport 
    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ${{ env.working-directory }}
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
