name: Lint
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - develop
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@master
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.49.0
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
