name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Starport
        run: go install ./...

      - name: Run Integration Tests
        run: ./scripts/test-integration 
