name: Integration
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - develop

jobs:
  pre-test:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*
            !**/*.md
      - name: Finding files and store to output
        id: set-matrix
        run: echo "::set-output name=matrix::$({ cd integration && find . -type d -maxdepth 1 -print; } | tail -n +2 | cut -c 3- | jq -R . | jq -cs .)"

  integration:
    name: test ${{ matrix.test-path }}
    runs-on: ubuntu-latest
    needs: pre-test
    if: env.GIT_DIFF && fromJSON(needs.pre-test.outputs.matrix)[0] != null
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        test-path: ${{fromJson(needs.pre-test.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Starport
        run: go install ./...
      - name: Run Integration Tests
        run: go test -v -timeout 30m ./integration/${{ matrix.test-path }}

  status:
    runs-on: ubuntu-latest
    needs: integration
    if: always()
    steps:
      - name: Update result status
        run: |
          if [ "${{ needs.integration.result }}" = "failure" ]; then
              exit 1
          else
              exit 0
          fi
