name: Test-Integration

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Starport
        run: go install ./...

      # integration tests should run on Go 1.15 until following issue has solved:
      # https://github.com/golang/go/issues/44129
      - name: "Get Go 1.15"	
        run: |	
          go get golang.org/dl/go1.15	
          go1.15 download	

      - name: Run Integration Tests
        run: ./scripts/test-integration 
        env:
          GONAME: "go1.15"
